name: Deploy to test server
run-name: ${{ github.actor }} is deploying to test server
on: [push]
jobs:
  Build-Deploy-Testing:
    runs-on: ubuntu-latest
    steps:
      - name: Create SSH key
        shell: bash
        env:
          SSH_PRIVATE_KEY: ${{secrets.secrets.OPENBSD_7_4_TESTING}}
          SSH_HOST: ${{secrets.OPENBSD_7_4_TESTING_HOST}}
        run: |
          mkdir -p /home/runner/.ssh/
          touch /home/runner/.ssh/known_hosts
          echo $SSH_PRIVATE_KEY > /home/runner/.ssh/id_ed25519
          ssh-keygen -yf /home/runner/.ssh/id_ed25519
          sudo chmod u=r,g=,o= /home/runner/.ssh/id_ed25519
          ssh-keyscan $SSH_HOST > /home/runner/.ssh/known_hosts
      - name: Prepare dependencies
        run: |
          sudo apt install libwebsockets-dev
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Make
        run: |
          cd ${{github.workspace}}
          make
      - name: Upload
        env:
          SSH_HOST: ${{secrets.OPENBSD_7_4_TESTING_HOST}}
        run: |
          cd ${{github.workspace}}
          scp -i /home/runner/.ssh/id_ed25519 target/flare_server testing@${{ secrets.OPENBSD_7_4_TESTING_HOST }}:~/