name: Deploy to test server
run-name: ${{ github.actor }} is deploying to test server
on: [push]
jobs:
  Build-Deploy-Testing:
    runs-on: ubuntu-latest
    steps:
      - name: Create SSH key
        shell: bash
        env:
          SSH_PRIVATE_KEY: ${{secrets.secrets.OPENBSD_7_4_TESTING}}
          SSH_HOST: ${{secrets.OPENBSD_7_4_TESTING_HOST}}
        run: |
          command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client wget gnupg -y )
          eval $(ssh-agent -s)
          echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
          mkdir -p /home/runner/.ssh/
          touch /home/runner/.ssh/known_hosts
          ssh-keyscan $SSH_HOST > /home/runner/.ssh/known_hosts
      - name: Prepare dependencies
        run: |
          sudo apt install libwebsockets-dev
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Make
        run: |
          cd ${{github.workspace}}
          make
      - name: Upload
        env:
          SSH_HOST: ${{secrets.OPENBSD_7_4_TESTING_HOST}}
        run: |
          cd ${{github.workspace}}
          scp target/flare_server testing@${{ secrets.OPENBSD_7_4_TESTING_HOST }}:~/