name: Deploy to test server
run-name: ${{ github.actor }} is deploying to test server
on: [push]
jobs:
  Build-Deploy-Testing:
    runs-on: ubuntu-latest
    steps:
      - name: Build artifact
        run: >
          sudo apt install libwebsockets-dev
          make
      - name: Upload binary
        run: >
          mkdir -p /home/runner/.ssh
          ssh-keyscan ${{ secrets.OPENBSD_7_4_TESTING_HOST }} >> /home/runner/.ssh/known_hosts
          echo "${{ secrets.OPENBSD_7_4_TESTING }}" > /home/runner/.ssh/privkey
          chmod 600 /home/runner/.ssh/privkey
          scp -i /home/runner/.ssh/privkey target/flare_server testing@${{ secrets.OPENBSD_7_4_TESTING_HOST }}:~/