name: Deploy to test server
run-name: ${{ github.actor }} is deploying to test server
on: [push]
jobs:
  Build-Deploy-Testing:
    runs-on: ubuntu-latest
    steps:
      - name: Create SSH key
        shell: bash
        env:
          SSH_PRIVATE_KEY: ${{secrets.secrets.OPENBSD_7_4_TESTING}}
          SSH_HOST: ${{secrets.OPENBSD_7_4_TESTING_HOST}}
        run: |
          mkdir -p ~/.ssh/ \
          touch ~/.ssh/known_hosts \
          echo "$SSH_PRIVATE_KEY" > ~/privkey \
          sudo chmod 600 ~/privkey \
          ssh-keyscan $SSH_HOST > ~/.ssh/known_hosts \
      - name: Prepare dependencies
        run: |
          sudo apt install libwebsockets-dev \
      - name: Make
        run: |
          make \
      - name: Upload
        env:
          SSH_HOST: ${{secrets.OPENBSD_7_4_TESTING_HOST}}
        run: |
          scp -i ~/privkey target/flare_server testing@${{ secrets.OPENBSD_7_4_TESTING_HOST }}:~/ \